# route:
#     receiver: 'slack'
#
# receivers:
#     - name: 'slack'
#       slack_configs:
#           - send_resolved: true
#             username: '<username>'
#             channel: '#<channel-name>'
#             api_url: '<incomming-webhook-url>'
#     - name: "alerta"
#        webhook_configs:
#            - url: 'http://alerta/api/webhooks/prometheus'
#              send_resolved: true
route:
  receiver: "alerta"
  group_by: ['alertname']
  group_wait:      15s
  group_interval:  15s
  repeat_interval: 1m

receivers:
- name: "alerta"
  webhook_configs:
  - url: 'http://alerta/api/webhooks/prometheus'
    send_resolved: true
    http_config:
      basic_auth: 
        username: admin@alerta.io
        password: alerta
