version: "3.8"

volumes:
  grafanadata:
  promdata: {}

services:
        db:
                image: postgres
                restart: always
                environment:
                        POSTGRES_DB: montd_monitdb
                        POSTGRES_USER: montdadm
                        POSTGRES_PASSWORD: montd_chg42
                ports:
                        - "5432"
        adminer:
                image: adminer
                restart: always
                ports:
                        - 8081:8080
        dash:
                image: grafana/grafana
                volumes:
                        - grafanadata:/var/lib/grafana
                ports:
                        - "3000:3000"
                environment:
                        - "GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,grafana-worldmap-panel,grafana-simple-json-datasource"
        prom:
                image: prom/prometheus
                volumes:
                        - ./prometheus:/etc/prometheus/
                        - promdata:/prometheus
                command:
                        - '--config.file=/etc/prometheus/prometheus.yml'
                        - '--storage.tsdb.path=/prometheus'
                        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
                        - '--web.console.templates=/usr/share/prometheus/consoles'
                ports:
                        - "9090:9090"
        alertaweb:
                image: alerta/alerta-web
                ports:
                        - "8080:8080"
                depends_on:
                        - db
                environment:
                        - DEBUG=1  # remove this line to turn DEBUG off
                        - DATABASE_URL=postgres://montdadm:montd_chg42@db:5432/montd_monitdb
                        - AUTH_REQUIRED=True
                        - ADMIN_USERS=admin@alerta.io,devops@alerta.io #default password: alerta
                        - ADMIN_KEY=demo-key
                        - PLUGINS=reject,blackout,normalise,enhance
                restart: always
        nodeexporter:
                image: prom/node-exporter:latest
                container_name: nodeexporter
                user: root
                privileged: true
                volumes:
                        - /proc:/host/proc:ro
                        - /sys:/host/sys:ro
                        - /:/rootfs:ro
                command:
                        - '--path.procfs=/host/proc'
                        - '--path.sysfs=/host/sys'
                        - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
                restart: unless-stopped
                ports:
                        - "9100:9100"
